### ISSUE TITLE
選曲画面の細かい演出の強化

### ISSUE THREAD

**Issue by renrentarou00553300** [TaikoCatsDooooN-team/TaikoCatsDooooN#15]
・ジャンルの画像描画時のアニメーション
・「閉じる」アニメーション
・開くときのアニメーションの改善
・さあ、始まるドン！どんちゃんの動き
・難易度選択画面時の右の難易度の背景?みたいなやつ
などなど・・・・・・・結構大変ですね(´・ω・｀)

**Comment by Moriumi** [comment]
関係性の薄いものは分けたほうがいいと思います

**Comment by renrentarou00553300** [comment]
関係性の薄いもの？

**Comment by Moriumi** [comment]
色々混ざってるので一度Closeしたほうがいいと思います。
