### ISSUE TITLE
Readme.mdがめちゃくちゃ

### ISSUE THREAD

**Issue by Skymint2270** [TaikoCatsDooooN-team/TaikoCatsDooooN#25]
## ロードマップみたいな

Ver.1.4.x : 細かいところの修正(真打コンボバルーン、画像修正など)

Ver.1.5.x : 段位認定機能の追加(TJAPlayer3 Ver1.5.3相当)
======================================================
Ver.1.5.x : 段位認定機能の追加と書いてあるが、すでにTCDNのバージョンは1.5.xだと思うのでおかしいと思いました

**Comment by miyaneko1467** [comment]
ec1783d で修正しました。
